name: Build and Zip Firefox Extension

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
 
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: 'yarn'
 
      - name: Install dependencies
        run: yarn
 
      - name: Build Chrome
        run: yarn build:firefox

      - name: Upload Firefox extension artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vite-web-extension-firefox
          path: dist_firefox